apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: server
  template:
    metadata:
      labels:
        service: server
    spec:
      containers:
       - name: server-service
         image: akashz/myapp:1.0
         imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: service-entrypoint
spec:
  type: LoadBalancer
  selector:
    service: server
  ports:
  - port: 8080
    targetPort: 8080
